// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 8.8
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container1").wowSlider({effect:"basic",prev:"",next:"",duration:15*100,delay:30*100,width:1024,height:640,autoPlay:true,autoPlayVideo:false,playPause:false,stopOnHover:false,loop:false,bullets:1,caption:true,captionEffect:"move",controls:true,controlsThumb:["data1/images/amaron.jpg", "data1/images/luk.jpg", "data1/images/dunlop.jpg", "data1/images/shell.jpg"],responsive:2,fullScreen:false,gestures:2,onBeforeStep:0,images:0});